[package]
name = "nrf24l01-embedded"
version = "0.2.0"
authors = ["Romuald Texier-Marcadé <romuadtm@gmail.com>", "Astro <astro@spaceboyz.net>"]
description = "A driver for NRF24L01(+) transceivers on embedded-hal platforms."
license = "MIT/Apache-2.0"
categories = ["embedded", "hardware-support"]
keywords = ["driver", "wireless", "radio", "transceiver", "nrf"]
repository = "https://github.com/astro/embedded-nrf24l01"
homepage = "https://github.com/astro/embedded-nrf24l01"

[dependencies]
nb = "*"
embedded-hal = "0.1.2"
# TODO:
cortex-m-semihosting = "*"
